//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystemPro.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.RentedBooks = new HashSet<RentedBook>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> PageCount { get; set; }
        public Nullable<System.DateTime> PublishingDate { get; set; }
        public int AuthorId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentedBook> RentedBooks { get; set; }
    }
}
